name: nightly

on:
  schedule:
    - cron: 0 2 * * *
  push:
    tags:
      - ciflow/nightly/*
  pull_request:
    paths:
      .github/workflows/nightly.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  update-pytorch-pin:
    runs-on: ubuntu-latest
    steps:
      - name: update-install-requirements-pytorch-nightly-version
        run: |
          set -eux
          sed -i '/dev20240716/dev20240717/' install_requirements.sh
          cat install_requirements.sh
